# Generated by Django 6.0.2 on 2026-03-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('newsapp.post',),
        ),
    ]
